docker-flask/website/shop/models.py
from website import db


class Product(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50))
    description = db.Column(db.Text)

    def __init__(self, name, description):
        self.name = name
        self.description = description

    def __repr__(self):
        return self.name

docker-flask/website/shop/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField
from wtforms.validators import DataRequired, optional, length


class CreateProductForm(FlaskForm):
    name = StringField('name', validators=[DataRequired()],
                       description='Product name')
    description = TextAreaField('description', validators=[
        optional(), length(max=200)], description='Product description')

docker-flask/website/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy

from config import config

bootstrap = Bootstrap()
db = SQLAlchemy()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])

    bootstrap.init_app(app)
    db.init_app(app)

    from .shop import shop as shopModule
    app.register_blueprint(shopModule)

    return app

docker-flask/website/shop/__init__.py
from flask import Blueprint

shop = Blueprint('shop', __name__)

from . import views

docker-flask/website/shop/views.py
from flask import render_template, redirect

from . import shop
from .forms import CreateProductForm
from .models import Product
from website import db


@shop.route('/', methods=['GET'])
def product_list():
    products = Product.query.all()
    return render_template('shop/product_list.html', products=products)


@shop.route('/create', methods=['GET', 'POST'])
def product_create():
    form = CreateProductForm()
    if form.validate_on_submit():
        product = Product(
            name=form.name.data,
            description=form.description.data,
        )
        db.session.add(product)
        db.session.commit()
        return redirect('/')
    return render_template('shop/product_create.html', form=form)

docker-flask/website/templates/_layouts/base.html
{% extends "bootstrap/base.html" %}

{% block styles %}
    {{super()}}
    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
{% endblock %}

{% block navbar %}
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="{{ url_for('shop.product_list') }}">Shop</a>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="jumbotron inner-jumbotron top">
        {% block shop_content %}
        {% endblock %}
    </div>

    {% block footer%}
        <hr>
        <p align="center"><i>2017</i></p>
    {% endblock %}
{% endblock %}

docker-flask/website/templates/shop/product_create.html
{% extends "_layouts/base.html" %}

{% block title %}Products - Create{% endblock %}

{% block shop_content %}
    <h2>Add new product</h2>
        <form method="POST" action="{{ url_for('shop.product_create') }}">
            {{ form.csrf_token }}
            <div class="form-group">
                <label>{{ form.name.label }}</label>
                {{ form.name(placeholder=form.name.description, class_="form-control") }}
            </div>
            <div class="form-group">
                <label>{{ form.description.label }}</label>
                {{ form.description(placeholder=form.description.description, class_="form-control") }}
            </div>
            <input type="submit" value="Submit">
            <input type="reset" value="Reset">
        </form>
    </div>
{% endblock %}

    

docker-flask/website/templates/shop/product_list.html
{% extends "_layouts/base.html" %}
{% block title %}Shop - Products{% endblock %}

{% block shop_content %}
    {% if products %}
        <h2>Product list</h2>
        <table class="table">
            <thead class="thead-inverse">
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                </tr>
            </thead>
            <tbody>
                {% for p in products %}
                    <tr>
                        <td>{{ p.name }}</td>
                        <td>{{ p.description }}</td>
                    </tr>
            
                {% endfor %}
            </tbody>
        </table>
    {% else %}
            <h2>There are no products yet</h2>
    {% endif %}
    <a href="{{ url_for('shop.product_create') }}" 
    class="btn btn-primary active">
        <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> Add Product
    </a>
{% endblock %}